"""initial

Revision ID: 0a50e4718831
Revises: 
Create Date: 2025-08-04 21:57:36.350252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a50e4718831'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gudang',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('lokasi', sa.String(), nullable=True),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gudang_id'), 'gudang', ['id'], unique=False)
    op.create_table('kategori',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=False),
    sa.Column('id_gudang', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_gudang'], ['gudang.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kategori_id'), 'kategori', ['id'], unique=False)
    op.create_table('supplier',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('telepon', sa.String(), nullable=False),
    sa.Column('alamat', sa.String(), nullable=False),
    sa.Column('id_gudang', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_gudang'], ['gudang.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.create_table('barang',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kd_barang', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=True),
    sa.Column('satuan', sa.Enum('pcs', 'kg', 'liter', name='satuan_enum'), nullable=False),
    sa.Column('harga_beli', sa.DECIMAL(), nullable=False),
    sa.Column('harga_jual', sa.DECIMAL(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('id_kategori', sa.String(), nullable=True),
    sa.Column('id_supplier', sa.String(), nullable=True),
    sa.Column('id_gudang', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_gudang'], ['gudang.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_supplier'], ['supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barang_id'), 'barang', ['id'], unique=False)
    op.create_index(op.f('ix_barang_kd_barang'), 'barang', ['kd_barang'], unique=True)
    op.create_table('transaksi',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jenis', sa.Enum('masuk', 'keluar', name='jenis_enum'), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.Column('id_barang', sa.String(), nullable=False),
    sa.Column('id_gudang', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_gudang'], ['gudang.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_id'), 'transaksi', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaksi_id'), table_name='transaksi')
    op.drop_table('transaksi')
    op.drop_index(op.f('ix_barang_kd_barang'), table_name='barang')
    op.drop_index(op.f('ix_barang_id'), table_name='barang')
    op.drop_table('barang')
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_kategori_id'), table_name='kategori')
    op.drop_table('kategori')
    op.drop_index(op.f('ix_gudang_id'), table_name='gudang')
    op.drop_table('gudang')
    # ### end Alembic commands ###
