"""update

Revision ID: 832612437783
Revises: 7a440f7419ee
Create Date: 2025-06-30 19:01:31.817486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832612437783'
down_revision: Union[str, Sequence[str], None] = '7a440f7419ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaksi',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jenis', sa.Enum('masuk', 'keluar', name='jenis_enum'), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.Column('id_barang', sa.String(), nullable=False),
    sa.Column('id_gudang', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_gudang'], ['gudang.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_id'), 'transaksi', ['id'], unique=False)
    op.drop_index(op.f('ix_supplier_id'), table_name='supplier')
    op.drop_table('supplier')
    op.add_column('barang', sa.Column('nama', sa.String(), nullable=False))
    op.drop_column('barang', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('barang', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('barang', 'nama')
    op.create_table('supplier',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('nama', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('telepon', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('alamat', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id_barang', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id'], name=op.f('supplier_id_barang_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('supplier_pkey')),
    sa.UniqueConstraint('id_barang', name=op.f('supplier_id_barang_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_supplier_id'), 'supplier', ['id'], unique=False)
    op.drop_index(op.f('ix_transaksi_id'), table_name='transaksi')
    op.drop_table('transaksi')
    # ### end Alembic commands ###
