"""update barang

Revision ID: d1973c7be3c4
Revises: 15e02ccbd7e9
Create Date: 2025-08-02 23:12:29.974953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1973c7be3c4'
down_revision: Union[str, Sequence[str], None] = '15e02ccbd7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barang_kd_barang'), table_name='barang')
    op.create_index(op.f('ix_barang_kd_barang'), 'barang', ['kd_barang'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barang_kd_barang'), table_name='barang')
    op.create_index(op.f('ix_barang_kd_barang'), 'barang', ['kd_barang'], unique=False)
    # ### end Alembic commands ###
